packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@scarf/scarf"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - core-js-pure
  - dprint
  - es5-ext
  - esbuild
  - msw
  - nx
  - puppeteer
  - sharp
  - sqlite3
  - unrs-resolver
