packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@suites/di.nestjs'
  - '@suites/doubles.jest'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js-pure
  - dprint
  - esbuild
  - nx
  - sharp
  - sqlite3
  - unrs-resolver
