---
extends: default
rules:
  line-length:
    max: 100
    level: warning
  comments:
    min-spaces-from-content: 1
    require-starting-space: false
  quoted-strings:
    required: only-when-needed
    extra-allowed: ["{|}"]
  key-duplicates: {}
  octal-values:
    forbid-implicit-octal: true
